### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ezrabro** [ssebs/csveditor#3]
can you please add 
requirements
and instructions for running the csveditor

and when i run the csveditor 
this thing happens
can you help?

Traceback (most recent call last):
  File "E:\Projects\csveditor\csveditor\csv_editor.py", line 2, in <module>
    from Tkinter import *
ModuleNotFoundError: No module named 'Tkinter'

**Comment by ssebs** [comment]
Sure, I will soon
For now, you can run `pip install tk`, or install using your package mgr
