### ISSUE TITLE
csveditor is an alternative for everything?

### ISSUE THREAD

**Issue by ghost** [ssebs/csveditor#6]

**Comment by ssebs** [comment]
@lucasnuic - Yeah basically, I created this more to learn how than anything else. I used it a bit but switched back to Excel.

If anything, I'm more interested in my [nccsv](https://github.com/ssebs/nccsv/) TUI CSV project.

**Comment by ssebs** [comment]
I think that's a good goal, but it might be better written in another language for performance.

**Comment by ssebs** [comment]
Sure, your account is marked as private so I can't just yet.

I'm open to pull requests if you have code to contribute.
